<?php
/**
 * @file
 * This module creates one more button in addition to existing one (Add to cart
 * button). The new button adds product item to shopping cart and redirects user
 * to /checkout page.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\commerce\commerce_product;


/**
 * Implements hook_form_alter().
 */
function commerce_one_click_buy_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (strstr($form_id, 'commerce_order_item_add_to_cart_form_commerce_product')) {
    $form['ocb_submit'] = array(
      '#type' => 'submit',
      '#name' => 'ocb',
      '#value' => t('One click buy'),
      '#submit' => array('_commerce_one_click_buy_submit'),
      '#weight' => '49',
    );
  }

}

/**
 * Adds an item to the shopping cart and redirect to checkout page.
 */
function _commerce_one_click_buy_submit(array $form, FormStateInterface $form_state) {
  global $user;
  drupal_set_message("Why won't this message show?");
  $cusers = $form_state->getValue(array('ocb_submit'));

  if (commerce_cart_product_add_by_id(1, 1, TRUE, $user->uid)) {
   // drupal_goto('checkout');
  }
  else {
    //drupal_set_message(t('Error occured during adding product to cart! Try to use Add to cart button.'));
  }

}
